version_set.cc: Remove unused num_empty_non_l0_level (clang warning)
This variable appears to be unused. It was added in commit db03739340
back in 2015, and it was unused then. I am guessing there may have
originally been some assert() statements that used this variable that
were removed?

Fixes the following warning on Mac OS X 14.4.1 with Apple clang 15:

db/version_set.cc:2853:7: error: variable 'num_empty_non_l0_level'
set but not used [-Werror,-Wunused-but-set-variable]