Replace static variables with constants.
Visual C++ rejects the previous code:
  error C2360: initialization of 'zlib_corrupt_msg' is skipped by 'case' label

These variables were unnecessarily introduced in
7521a225d1c16f591015b323c0a76cbb8d0cf8ae.