compression: fix clang warning unused
clang++-6.0 error:
./util/compression.h:110:9: error: private field 'padding' is not used [-Werror,-Wunused-private-field]
  void* padding;  // unused
        ^