Align StatisticsImpl to CACHE_LINE_SIZE so sharing as an effect
Pinned the alignment of StatisticsData to the cacheline size rather
than just extending its size (which could go over two cache lines)
if unaligned in allocation.

-faligned-new used if available (gcc-7) to avoid the error like:

./util/core_local.h: In instantiation of ‘rocksdb::CoreLocalArray<T>::CoreLocalArray() [with T = rocksdb::StatisticsImpl::StatisticsData]’:
monitoring/statistics.cc:26:77:   required from here
./util/core_local.h:51:15: error: ‘new’ of type ‘rocksdb::StatisticsImpl::StatisticsData’ with extended alignment 128 [-Werror=aligned-new=]
   data_.reset(new T[static_cast<size_t>(1) << size_shift_]);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./util/core_local.h:51:15: note: uses ‘void* operator new [](std::size_t)’, which does not have an alignment parameter
./util/core_local.h:51:15: note: use ‘-faligned-new’ to enable C++17 over-aligned new support