Temporary disable Travis s390x Makefile build
Summary: Due to some unexplained errors with gcc-7

```
Assembler messages:
Error: invalid switch -march=z14
Error: unrecognized option -march=z14
```

Test Plan: CI