Fix a clang analyzer report, and 'analyze' make rule
Summary: Clang analyzer was falsely reporting on use of txn=nullptr.
Added a new const variable so that it can properly prune impossible
control flows.

Also, 'make analyze' previously required setting USE_CLANG=1 as an
environment variable, not a make variable, or else compilation errors
like

g++: error: unrecognized command line option ‘-Wshorten-64-to-32’

Now USE_CLANG is not required for 'make analyze' and you can do an
incremental analysis (recompile what has changed) with 'USE_CLANG=1 make
analyze_incremental'

Test Plan: 'make -j24 analyze', 'make crash_test'