Fix/expand prefix extractor testing in crash test
Summary: Changes in #9453 could trigger
```
stderr:
Error: prefixpercent is non-zero while prefix_size is not positive!
```

Test Plan: run `make blackbox_crashtest` for a long time