Fix powerpc compilation with -Werror=unused-variable
Fixes the following error:

rocksdb/util/crc32c.cc:44:12: error: 'rocksdb::crc32c::arch_ppc_crc32' defined but not used [-Werror=unused-variable]
  static int arch_ppc_crc32 = 0;