Fix MinGW build
snprintf is defined as _snprintf, which doesn't exist in the std
namespace.

blob_file.cc: In member function 'std::__cxx11::string
rocksdb::blob_db::BlobFile::DumpState() const':
blob_file.cc:92:3: error: '_snprintf' is not a member of 'std'
   std::snprintf(str, sizeof(str),
   ^~~