Fix declaration scope of LE_LOAD32 in crc32c
Fix build error when __SSE4_2__ is defined:
util/crc32c.cc: In function 'void rocksdb::crc32c::DefaultCRC32(uint64_t*, const uint8_t**)':
util/crc32c.cc:267:53: error: 'LE_LOAD32' was not declared in this scope
  267 |   *l = _mm_crc32_u32(static_cast<unsigned int>(*l), LE_LOAD32(*p));
      |                                                     ^~~~~~~~~

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>