Likely fix flaky DBTest.SparseMerge
Summary: It looks like ages ago support for Universal compaction was
added to this test in a bulk way, and probably kept because the test
passes. But I don't think it's appropriate for universal compaction
where entire levels are compacted. A flaky failure looks like this:

WARNING: c:\users\circleci\project\db\db_test.cc(1343): error: Expected:
(dbfull()->TEST_MaxNextLevelOverlappingBytes(handles_[1])) <= (20 * 1048576), actual: 33501540 vs 20971520

I suspect this arises from some skew in multilevel universal, which
normally has nearly 20MB in L1 and 80+MB in L6. I don't know why the
behavior is sometimes different, but I don't think it's relevant to
the purpose of the test.

Also fixed apparently missing column family in CompactRange calls.

Test Plan: we'll see