Fix a nuisance compiler warning from clang
Summary: Example:

```
cache/clock_cache.cc:56:7: error: fallthrough annotation in unreachable code [-Werror
,-Wimplicit-fallthrough]
      FALLTHROUGH_INTENDED;
      ^
./port/lang.h:10:30: note: expanded from macro 'FALLTHROUGH_INTENDED'
                             ^
```

In clang < 14, this is annoyingly generated from -Wimplicit-fallthrough, but
was changed to -Wunreachable-code-fallthrough (implied by -Wunreachable-code)
in clang 14. See https://reviews.llvm.org/D107933 for how this nuisance
pattern generated false positives similar to ours in the Linux kernel.

Test Plan: Added the warning to our Makefile for USE_CLANG, which
reproduced the warning-as-error as shown above, but is now fixed.